name: Java CI with Maven

on:
  push:


env:
  DB_DATABASE: fullstack
  DB_ROOT_PASSWORD: root
  DB_USER: fullstack
  DB_PASSWORD: fullstack

jobs:

  build:


    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: ${{ env.DB_DATABASE }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.DB_ROOT_PASSWORD }}
        ports:
          - 33306:3306

    steps:
      - name: Grant privileges to fullstack
        run:
          sudo /etc/init.d/mysql start
          mysql -uroot -proot -e "GRANT REFERENCES ON fullstack.* TO 'fullstack'@'localhost'";
      - name: Branch Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
