name: Full Stack Project CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'fullstack'
        mysql user: 'fullstack'
        mysql password: 'fullstack'
    - name: Branch Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
